ДЗ 5
ilshat-husnutdinov/2022-2-VK-EDU-FS-Frontend-I-Husnutdinov pull request #5
Opened 2022-11-14 08:42 UTC by ilshat-husnutdinov

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* Переписаны компоненты на React
* Восстановлены стили, функциональность компонентов и переход по страницам
* Перенастроен деплой из новой директории react-chat

2022-11-19 19:48 UTC, martinkomitsky commented on react-chat/src/components/ChatListComponents/CreateChatBlock/CreateChat.css
> +    -moz-box-shadow: 0 0 0 0 rgba(204,169,44, 0.4);
все префиксные стили не нужны. Их автоматом проставят при сборке

2022-11-19 19:50 UTC, martinkomitsky commented on react-chat/src/components/ChatIcons/More/More.css
> +#more_vert:hover {
стоит переделать практические все селекторы, которые есть в проекте. 
Очень советую переделать на [`css modules`])https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/)
Избавиться от каскадов, айдишников, использования комбинаторов типа `>`. Везде должны остаться классы

2022-11-19 19:51 UTC, martinkomitsky commented on react-chat/src/components/ChatIcons/Menu/Menu.jsx
> +             <span className="material-icons">menu</span>
Заменить на иконки из пакета material-icons. В условии дз есть ссылка

2022-11-19 19:51 UTC, martinkomitsky commented on react-chat/src/components/ChatIcons/More/More.jsx
> +        window.addEventListener('click', function(e) {
нет, в реакте так уже делать не стоит. Есть конкретные элементы и свойство `onClick`

2022-11-19 19:53 UTC, martinkomitsky requested changes
Исправить по комментам

2022-11-20 16:10 UTC, ilshat-husnutdinov commented on react-chat/src/components/ChatIcons/More/More.jsx
> +        window.addEventListener('click', function(e) {
То есть обращаться к глобальному объекту `window` и регистрировать обработчик событий через `.addEventListener` не стоит? Просто в этой части кода я реализую закрытие выпадающего меню при клике вне React-компонента `More` и данный подход был одним из часто применяемых, который я нашёл на просторах интернета.

![image](https://user-images.githubusercontent.com/113860500/202912729-2cd46da5-0e40-48af-9387-a11be0ad88de.png)

2022-11-20 16:23 UTC, ilshat-husnutdinov commented
Исправил замечания по всем комментариям, кроме одного (я оставил под ним свой вопрос, хотелось бы уточнить).

2022-11-22 12:03 UTC, martinkomitsky commented on react-chat/src/components/ChatComponents/MessageBlock/Messages.jsx
> +		scroll(styles.message);
очень изящно. Вообще, желательно такие вещи делать через `ref`
https://reactjs.org/docs/hooks-reference.html#useref

Можно к следующему ДЗ исправить на рефы)

2022-11-22 12:05 UTC, martinkomitsky commented on react-chat/src/components/ChatIcons/More/More.jsx
> +        window.addEventListener('click', function(e) {
ок, понял тебя. В принципе, можно оставить, но тогда обязательно сделать отписку от события. Сейчас с каждым открытием дропдауна у тебя будет навешиваться этот обработчик, а сниматься - нет. Отсюда и будут утечки.
Посмотри запись (или слайды) последней лекции, там есть пример, как правильно делать подписку/отписку от событий

2022-11-22 12:05 UTC, martinkomitsky requested changes
Сделать еще пару фиксов

2022-11-23 11:02 UTC, ilshat-husnutdinov commented
Сделано

2022-11-24 08:55 UTC, martinkomitsky approved these changes
10

2022-11-24 08:55 UTC, merged